### ISSUE TITLE
Where is requirements.txt ?

### ISSUE THREAD

**Issue by 5e4** [peterkruse/DiscordMassAccountCreator#2]
hi mate , I cant find requirements.txt so I cant run the software.

**Comment by peterkruse** [comment]
Hi.

Sorry, i havent have time to upload requirements.txt 👍🏼 

thanks for notifying me.

**Comment by 5e4** [comment]
thanks

**Comment by peterkruse** [comment]
Your welcome

**Comment by peterkruse** [comment]
Your welcome
